<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Dexie.Cards.Api</RootNamespace>
    <AssemblyName>Dexie.Cards.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../../../backend/libs/dexie-domain/src/Dexie.Shared.Domain/Dexie.Shared.Domain.csproj" />
    <ProjectReference Include="../../../../../backend/libs/dexie-infra/src/Dexie.Shared.Infrastructure/Dexie.Shared.Infrastructure.csproj" />
  </ItemGroup>

</Project>
